# Generated by Django 3.1.7 on 2021-03-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biosamples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst', to='biosamples.biosample')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src', to='biosamples.biosample')),
            ],
        ),
    ]
