# Generated by Django 3.1.7 on 2021-04-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosamples', '0002_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosample',
            name='assay',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosample',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='biosample',
            name='condition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biosample',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='biosample',
            name='layout',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='biosample',
            name='organism',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='biosample',
            name='platform',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='biosample',
            name='target',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='biosample',
            name='treatment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biosample',
            name='treatment_conc',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='biosample',
            name='treatment_time',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='sample_name',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='similarity',
            unique_together={('src', 'dst')},
        ),
    ]
